spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

mybatis:
  #  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.eternity.cloud.cloudapi.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: cloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.190.208.1:3306/clouddb01?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 6231989zh
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  # 客户端注册进eureka服务列表内
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka
  # 修改eureka监控中的实例名称
  instance:
    instance-id: cloud-dept8001
    # 访问路径可以显示IP地址
    prefer-ip-address: true

info:
  app.name: eternity-cloud
  company.name: eternityz.store
  # ${project.artifactId}形式也可以读取值
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001

mybatis:
  #  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.eternity.cloud.cloudapi.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: cloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.190.208.1:3306/clouddb02?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 6231989zh
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  # 客户端注册进eureka服务列表内
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka
  # 修改eureka监控中的实例名称
  instance:
    instance-id: cloud-dept8001
    # 访问路径可以显示IP地址
    prefer-ip-address: true

info:
  app.name: eternity-cloud
  company.name: eternityz.store
  # ${project.artifactId}形式也可以读取值
  build.artifactId: $project.artifactId$
  build.version: $project.version$